name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.2'

      - name: Dependencies
        run: go get ./...

      - name: Build
        run: GOOS=linux go build -o main *.go

      - name: Package
        run: zip -r archive.zip main

      - name: Store
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: archive.zip
  deploy:
    name: Deploy
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Download Build Archive
        uses: actions/download-artifact@v2
        with:
          name: build-artifact

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve
